// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeminarManagement.Database.EFCore;

namespace SeminarManagement.Database.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeminarMnagamenet.Models.ConfrenceRome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfrenceRomes");
                });

            modelBuilder.Entity("SeminarMnagamenet.Models.Lectur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lecturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SeminarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeminarId");

                    b.ToTable("Lecturs");
                });

            modelBuilder.Entity("SeminarMnagamenet.Models.Seminar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfrenceRomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LengthOfTIME")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfrenceRomeId");

                    b.ToTable("Seminars");
                });

            modelBuilder.Entity("SeminarMnagamenet.Models.Lectur", b =>
                {
                    b.HasOne("SeminarMnagamenet.Models.Seminar", "Seminar")
                        .WithMany("Lecturs")
                        .HasForeignKey("SeminarId");
                });

            modelBuilder.Entity("SeminarMnagamenet.Models.Seminar", b =>
                {
                    b.HasOne("SeminarMnagamenet.Models.ConfrenceRome", "ConfrenceRome")
                        .WithMany("Seminars")
                        .HasForeignKey("ConfrenceRomeId");
                });
#pragma warning restore 612, 618
        }
    }
}
